### ISSUE TITLE
build missing

### ISSUE THREAD

**Issue by webmandman** [kendo-labs/bower-kendo-ui#15]
telerik/kendo-ui-core includes a custom build process that I think should be available to bower installs. ideally I would like to:
bower install kendo-ui-core
gulp kendo-build all or kendo-build autocomplete dropdownlist
  ---> which executes your "grunt custom:autocomplete,dropdownlist" task. 
  ---> then my "gulp src2dest" task

I'm trying to do it this since I could not get bower to install kendo-ui-core from URL: https://github.com/telerik/kendo-ui-core.git

**Comment by underlog** [comment]
Hi, 

This is a reasonable workflow, indeed. However, due to multiple customer suggestions, we are about to remove the `src` directory from this repository, because it includes a lot of source files people rarely use (and it results in a ~10MB additional load). 

In order to facilitate the scenario you describe, we consider introducing another repository which contains the source files, too.
